global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'scrapping-recsys_app'

    metrics_path: /metrics
    scheme: http
    
    static_configs:
    - targets:
      - recsys_app:7000
